package vtimea.kcalculator.data;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

import java.util.Date;
import org.greenrobot.greendao.annotation.Generated;

@Entity
public class FoodItem {
    @Id(autoincrement = true)
    private Long id;    //generated by greenDAO

    private String description; //name or description of food

    @NotNull
    private int cals;   //calorie content of food

    @NotNull
    private Date date;  //date of consumption

    private String photoLocation; //id of the photo which is attached to the food (if there's one)

    @Generated(hash = 1225716941)
    public FoodItem(Long id, String description, int cals, @NotNull Date date, String photoLocation) {
        this.id = id;
        this.description = description;
        this.cals = cals;
        this.date = date;
        this.photoLocation = photoLocation;
    }
    @Generated(hash = 502595677)
    public FoodItem() {
    }

    //Getter and setter methods
    public Long getId(){ return id; }
    public void setId(Long id){ this.id = id; }
    public String getDescription(){ return description; }
    public void setDescription(String description){ this.description = description; }
    public int getCals(){ return cals; }
    public void setCals(int cals){ this.cals = cals; }
    public Date getDate(){ return date; }
    public void setDate(Date date){ this.date = date; }
    public String getPhotoLocation(){ return photoLocation; }
    public void setPhotoLocation(String photoLocation){ this.photoLocation = photoLocation; }
}
